import type { Metadata } from "next";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import "./globals.css";
import DashboardAside from "./dashboard/@aside/page";

export const metadata: Metadata = {
  title: "ERP System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="antialiased">
          <SignedIn>
            <div className="flex min-h-screen">
              <aside className="w-64 bg-gray-100 p-6 border-r">
                <DashboardAside />
              </aside>
              <main className="flex-1 p-8 bg-white">{children}</main>
            </div>
          </SignedIn>
          <SignedOut>{children}</SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
